### ISSUE TITLE
brainstorming new project 1

### ISSUE THREAD

**Issue by gabrielchasukjin** [dsc-courses/dsc80-2024-sp#10]
https://docs.google.com/document/d/1-ND6eIO1tTmU0SHvRTGb26N97KU2JpRztYSKndZmaMo/edit#heading=h.ptuvrmt77zx2

**Comment by SamLau95** [comment]
this looks awesome! excited to talk about it.

**Comment by SamLau95** [comment]
closing since we're going to start outlining the project now.
