### ISSUE TITLE
update course website calendar page, tech support page, staff page

### ISSUE THREAD

**Issue by SamLau95** [dsc-courses/dsc80-2024-sp#5]
also, need to remember to update ed, github, and gradescope links on website.

**Comment by SamLau95** [comment]
praveen can assign to a tutor once we decide who's in charge of infrastructure

**Comment by pnair7** [comment]
@Ari-03, sorry to assign this to you late -- message me for the staff info from the form responses, and let me know if you want me to do any of the website editing

**Comment by gabrielchasukjin** [comment]
I can help with this (if needed) and have it completed by EOD April 1. 

I'm assuming we have to update the `late policy` in the syllabus,  as well.  Can help draft this section !
