### ISSUE TITLE
schedule alternate staff meeting slot for staff who can't make normal meeting time

### ISSUE THREAD

**Issue by SamLau95** [dsc-courses/dsc80-2024-sp#8]

**Comment by SamLau95** [comment]
@pnair7 were you able to schedule another meeting time for people who can't make it on fridays?

**Comment by pnair7** [comment]
I asked if anyone wasn't able to make the weekly meetings in the Slack message I sent with the onboarding + OH signup and nobody got back to me, but I'll send another message right now to make sure

**Comment by pnair7** [comment]
Unless the idea is that there'll be a standing time for anyone who can't make it on Fridays on a week-to-week basis, which I can do, but I'm not sure that's what you mean.

**Comment by SamLau95** [comment]
okay, sounds good! in the original when2meet i think a few people said they couldn't make the friday 1-2pm slot, but if that turns out to work for everyone then we're good to go here :)

**Comment by pnair7** [comment]
I've set up a time (during her office hours) to talk to Mizuho today (she'll be back next week), but nobody else seemed to have an issue with the staff meeting time, so I'm closing the issue.
